### PR TITLE
Add several citations

### LINKED ISSUE #55: Applied Differential Equations by Vladimir Dobrushkin
Applied Differential Equations. The Primary Course by Vladimir Dobrushkin, CRC Press, 2015; http://www.crcpress.com/product/isbn/9781439851043

via http://www.cfm.brown.edu/people/dobrush/am33/sage/

### LINKED ISSUE #68: add 'Reduction of dimension for nonlinear dynamical systems'
```
@Article{Harrington2017,
author="Harrington, Heather A.
and Van Gorder, Robert A.",
title="Reduction of dimension for nonlinear dynamical systems",
journal="Nonlinear Dynamics",
year="2017",
volume="88",
number="1",
pages="715--734",
abstract="We consider reduction of dimension for nonlinear dynamical systems. We demonstrate that in some cases, one can reduce a nonlinear system of equations into a single equation for one of the state variables, and this can be useful for computing the solution when using a variety of analytical approaches. In the case where this reduction is possible, we employ differential elimination to obtain the reduced system. While analytical, the approach is algorithmic and is implemented in symbolic software such as MAPLE or SageMath. In other cases, the reduction cannot be performed strictly in terms of differential operators, and one obtains integro-differential operators, which may still be useful. In either case, one can use the reduced equation to both approximate solutions for the state variables and perform chaos diagnostics more efficiently than could be done for the original higher-dimensional system, as well as to construct Lyapunov functions which help in the large-time study of the state variables. A number of chaotic and hyperchaotic dynamical systems are used as examples in order to motivate the approach.",
issn="1573-269X",
doi="10.1007/s11071-016-3272-5",
url="http://dx.doi.org/10.1007/s11071-016-3272-5"
}
```

### LINKED ISSUE #71: add Towards a complete classification of fermionic symmetry protected topological phases in 3D and a general group supercohomology theory
```
@ARTICLE{2017arXiv170310937W,
   author = {{Wang}, Q.-R. and {Gu}, Z.-C.},
    title = "{Towards a complete classification of fermionic symmetry protected topological phases in 3D and a general group supercohomology theory}",
  journal = {ArXiv e-prints},
archivePrefix = "arXiv",
   eprint = {1703.10937},
 primaryClass = "cond-mat.str-el",
 keywords = {Condensed Matter - Strongly Correlated Electrons, High Energy Physics - Theory, Mathematical Physics},
     year = 2017,
    month = mar,
   adsurl = {http://adsabs.harvard.edu/abs/2017arXiv170310937W},
  adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}
```

### LINKED ISSUE #87: Add Sandpiles book by Perkinson and Corry
https://bookstore.ams.org/mbk-114/

Cites SageMath as "which has extensive built-in support for divisors and sandpiles."

### LINKED ISSUE #92: Add Shemanske Elliptic/Crypto book
This book http://www.ams.org/publications/authors/books/postpub/stml-83 states "all code and figures in the text were produced with Sage"

### LINKED ISSUE #93: add "Computational Mathematics with SageMath"
"Computational Mathematics with SageMath" has appeared as SIAM book:

http://bookstore.siam.org/ot160/

### LINKED ISSUE #110: add "Conformal evolution of phantom dominated final stages of the universe in higher dimensions"
"Conformal evolution of phantom dominated final stages of the universe in higher dimensions" is published in the Canadian Journal of Physics. The work implements SageManifold package. We thank sagemath on this great occasion.

DoI: https://doi.org/10.1139/cjp-2019-0626

Paper: https://www.nrcresearchpress.com/doi/abs/10.1139/cjp-2019-0626

```
@article{doi:10.1139/cjp-2019-0626,
author = {Natarajan, S. and Chandramohan, R.},
title = {Conformal evolution of phantom dominated final stages of the universe in higher dimensions},
journal = {Canadian Journal of Physics},
volume = {0},
number = {ja},
pages = {null},
year = {0},
doi = {10.1139/cjp-2019-0626},

URL = { 
        https://doi.org/10.1139/cjp-2019-0626
    
},
eprint = { 
        https://doi.org/10.1139/cjp-2019-0626
    
}

}
```

### LINKED ISSUE #114: add "Symbolic and Numerical Analysis in General Relativity with Open  Source Computer Algebra Systems"
Tolga Birkandan, Ceren Guzelgun, Elif Sirin, Mustafa Can Uslu, 
"Symbolic and Numerical Analysis in General Relativity with Open 
Source Computer Algebra Systems", General Relativity and Gravitation 
51, 4 (2019) (arXiv: 1703.09738 [gr-qc])

https://link.springer.com/article/10.1007/s10714-018-2486-x

### LINKED ISSUE #141: add paper and book by  Olivier Ramaré
```
@article {Ettahri-Ramare-Surel*19,
     AUTHOR = {Ettahri, S. and Ramar\'{e}, O. and Surel, L.},
      TITLE = {Fast multi-precision computation of some {E}uler products},
    JOURNAL = {Math. Comp.},
   FJOURNAL = {Mathematics of Computation},
     VOLUME = {90},
       YEAR = {2021},
     NUMBER = {331},
      PAGES = {2247--2265},
       ISSN = {0025-5718},
    MRCLASS = {11Y60},
   MRNUMBER = {4280300},
        DOI = {10.1090/mcom/3630},
       NOTE = {https://ramare-olivier.github.io/Maths/mcom3630.pdf},
}
```

```
@article {Ramare*20a,
     AUTHOR = {Ramar\'{e}, O.},
      TITLE = {Accurate computations of {E}uler products over primes in
               arithmetic progressions},
    JOURNAL = {Funct. Approx. Comment. Math.},
   FJOURNAL = {Uniwersytet im. Adama Mickiewicza w Poznaniu. Wydzia\l
               Matematyki i Informatyki. Functiones et Approximatio
               Commentarii Mathematici},
     VOLUME = {65},
       YEAR = {2021},
     NUMBER = {1},
      PAGES = {33--45},
       ISSN = {0208-6573},   MRCLASS = {11Y60 (05A15 11N13)},
   MRNUMBER = {4311494},
        DOI = {10.7169/facm/1853},
       NOTE = {https://ramare-olivier.github.io/Maths/FA1853.pdf},
}
```

Available (on my web page) at

https://ramare-olivier.github.io/Maths/mcom3630.pdf

https://ramare-olivier.github.io/Maths/FA1853.pdf

The first paper describes a software (available where it says it is :)):

--------------------------------------------------------------------------------

```
@Misc{Ramare*21-s,
author =   {O. Ramar\'e},
title =    {{Sage}: {C}omputing {L}attice {I}nvariant {E}uler {P}roducts
{L}ibrary},
url =
{https://ramare-olivier.github.io/Maths/LatticeInvariantEulerProducts-06.sage},
year = {2020}
}
```

---------------------------------------------------------------------------------

I've also written a book:

```
@book {Ramare*22-0,
     AUTHOR = {Ramar\'e, Olivier},
      TITLE = {Excursions in {M}ultiplicative {N}umber {T}heory},
     SERIES = {Birkh\"{a}user Advanced Texts: Basler Lehrb\"{u}cher.
[Birkh\"{a}user Advanced Texts: Basel Textbooks]},
       NOTE = {With the collaboration of P. Moree and A. Sedunova},
  PUBLISHER = {Birkh\"{a}user/Springer, Cham},
ISSN = {1019-6242},
       YEAR = {[2022] \copyright 2022},
      PAGES = {xxii+338},
}
```

### LINKED ISSUE #146: add "Limit heights and special values of the Riemann zeta function"
- Title: Limit heights and special values of the Riemann zeta function
- Authors: Roberto Gualdi, and Martín Sombra
- Link: https://arxiv.org/abs/2304.01966

```
@misc{gualdi2023limit,
      title={Limit heights and special values of the Riemann zeta function}, 
      author={Roberto Gualdi and Martín Sombra},
      year={2023},
      eprint={2304.01966},
      archivePrefix={arXiv},
      primaryClass={math.NT}
}

### LINKED ISSUE #147: Add paper by Melitsas in JNT
https://www.sciencedirect.com/science/article/abs/pii/S0022314X2200230X

A divisibility related to the Birch and Swinnerton-Dyer conjecture

https://arxiv.org/abs/2211.08147

### LINKED ISSUE #151: Add Squigonometry
Not in the references but mentioned as helping with graphics and computations in the book.

https://link.springer.com/book/10.1007/978-3-031-13783-9

### LINKED ISSUE #152: Add Numberverse
[This book](https://link.springer.com/book/10.1007/978-3-030-98931-6) has some Sage activities in it.

### LINKED ISSUE #153: Add Math Mag Cubes paper
The article https://www.tandfonline.com/doi/full/10.1080/0025570X.2023.2266345 by Charest, Coté, and Heilman cites Sage.

### LINKED ISSUE #154: Add Math Mag scheduling paper from 2024
The paper by Jeff Denny, *Schedules and Waitlists and Integer Programs, Oh My!* https://www.tandfonline.com/doi/full/10.1080/0025570X.2023.2284419 mentions using (but doesn't cite) Sage - interestingly, using GLPK, not the usual Sage usage but good that we have those interfaces!

### LINKED ISSUE #160: Constraining Gaussian processes to systems of linear ordinary differential equations
Besginow, Andreas, and Markus Lange-Hegermann. "Constraining Gaussian processes to systems of linear ordinary differential equations." Advances in Neural Information Processing Systems 35 (2022): 29386-29399.

[1]  https://proceedings.neurips.cc/paper_files/paper/2022/file/bcef27c5825d1ed8757290f237b2d851-Paper-Conference.pdf 

```
@article{besginow2022constraining,
  title={Constraining Gaussian processes to systems of linear ordinary differential equations},
  author={Besginow, Andreas and Lange-Hegermann, Markus},
  journal={Advances in Neural Information Processing Systems},
  volume={35},
  pages={29386--29399},
  year={2022}
  note={https://proceedings.neurips.cc/paper_files/paper/2022/file/bcef27c5825d1ed8757290f237b2d851-Paper-Conference.pdf}
}

### PR DESCRIPTION
**Pull request by AdityaK1729**
Fixes #160, Fixes #154, Fixes #153, Fixes #152, fixes #151, fixes #147, fixes #146, fixes #141, fixes #114, fixes #110, fixes #87, fixes #92, fixes #93, fixes #68, fixes #71, fixes #55 (some of these were already fixed, with issue still being listed as open, so i have tagged those as well)

### CODE REVIEW

**Comment by AdityaK1729** [comment]
I have ran the checks (looks so atleast) so i think this can be merged now

**Comment by AdityaK1729** [comment]
> wow, thank you!!! 🥳
always welcome :), can you tell me now how do i proceed with undetstanding the main codebase and making some contrinutions there
thanks :)

**Comment by haraldschilly** [comment]
Main codebase of Sage? I'm really the wrong person to ask, sorry. But there is an entire handbook for doing sage development: https://doc.sagemath.org/html/en/developer/

**Comment by kcrisman** [comment]
> wow, thank you!!! 🥳
>
>
Yes!  This was sorely needed, very much appreciated.

**Comment by roed314** [comment]
> oh nvm, thanks regardless :)

One place to get help is sagemath.zulipchat.com, once you take a look at the developer guide, the [open issues](https://github.com/sagemath/sage/issues) and think about what parts of Sage you would like to contribute to.

**Pull request merged**
