### PR TITLE
Add Infinite families of standard Cappell-Shaneson spheres

### LINKED ISSUE #155: add "Infinite families of standard Cappell-Shaneson spheres"
> I have cited SageMath in my paper, https://doi.org/10.48550/arXiv.2404.05096, so I would like you to write my paper information on the web page, https://www.sagemath.org/library-publications.html.

```
@misc{iwaki2024infinite,
      title={Infinite families of standard Cappell-Shaneson spheres}, 
      author={Kazunori Iwaki},
      year={2024},
      eprint={2404.05096},
      archivePrefix={arXiv},
      primaryClass={math.GT}
}
```

### PR DESCRIPTION
**Pull request by AdityaK1729**
fixes #155

### CODE REVIEW

**Comment by haraldschilly** [comment]
Thank you! FYI, the "check" is [here](https://github.com/sagemath/publications/actions/runs/11159404454/job/31018102085?pr=158) (linked in the box above).

**Comment by AdityaK1729** [comment]
can you tell me more about checks, as i am new to this, like was I supposed to run those by ourself, if yes how can I do that in the future

**Comment by haraldschilly** [comment]
> checks

The whole point is to avoid merging changes, which break the build process. So, e.g. if the syntax is wrong or whatever, the python script processing it will fail.

In this case here, the "check" runs that script, and the check passes if it does complete successfully.

As an external contributor, someone who owns the repository has to active running the checks – that's what I did. Then the check ran with your change. There was no error. Then I merged it.

If there would have been an error, you can see the error message. Then you're supposed to fix your code and push another commit. The check will run again.

The definition of what's going on in the check is here – in particular the last line: https://github.com/sagemath/publications/blob/master/.github/workflows/check.yml

**Comment by AdityaK1729** [comment]
that helps thanks

**Pull request merged**
