### PR TITLE
fix defaults for dicts .get(...) calls

### PR DESCRIPTION
**Pull request by dimpase**
This allows using `journal` without `journaltitle`, etc.

### CODE REVIEW

**Comment by haraldschilly** [comment]
looks good, thank you! my test was to check the sha1sums of the previously generated artefacts, then update all of them using the new code and, without surprise, sha1sums are the same 🥳 

```
~/website/publications$ sha1sum *.html
04e430ca8d9bf23ef13e7c16f053a9dc0f89fa83  publications-combinat.html
3768809a2388b75933688cdca4538347eb1648bf  publications-general.html
cefc1b2e8480261370e7e53be748aee2b355fe79  publications-mathscinet.html
1c6435038c9eb624ad3864e984e750980fbbe1b7  publications-mupad.html
~/website/publications$ make clean; make
[...]
~/website/publications$ sha1sum *.html
04e430ca8d9bf23ef13e7c16f053a9dc0f89fa83  publications-combinat.html
3768809a2388b75933688cdca4538347eb1648bf  publications-general.html
cefc1b2e8480261370e7e53be748aee2b355fe79  publications-mathscinet.html
1c6435038c9eb624ad3864e984e750980fbbe1b7  publications-mupad.html
```

**Comment by dimpase** [comment]
I tested my changes locally, by running `make` after changing few `journaltitle` to `journal` in one of .bib files. So from now on, `journal` should be fine.

Going forward, one should use a modern tool, e.g. Sphinx with a BibTeX extension, to produce property formatted webpages from .bib files.

**Comment by dimpase** [comment]
Is there any reason not to use make4ht+bibtex to produce a MathJax-enabled html out of bibfiles?  It will need a short .tex file to load
all the bibfiles, but then one can get rid of all this crude Python stuff.

**Comment by haraldschilly** [comment]
I'm not sure who you ask. I haven't written this tool, everything is possible I guess? From what I know about this, the basic constraints are to produce html code, which will then be embedded as it is on the sage website (i.e. no extras, just the plain list), and to be able to run this tool on Linux.

**Comment by dimpase** [comment]
It would for sure be much simpler, and solve problems of displaying TeX properly.

**Comment by dimpase** [comment]
e.g. I've done https://cddlib.github.io/polyhedral_faq/
this way. 
https://github.com/cddlib/polyhedral_faq

(even the deployment is done via GitHub's Actions, automatically)

**Pull request merged**
