### PR TITLE
added 8 paper by Cremona et al

### PR DESCRIPTION
**Pull request by JohnCremona**
I added 8 papers to bibliography-sage.bib, taking the Bibtex entries from Google Scholar but changing the tags to something more sensible.  I did a bit of massaging to get "make" to not object to my additions (though why I had to change "year" to "date" and "journal" to "journaltitle" is a mystery to me.  But make still chokes on at least one entry there not mine (Garfinkel-Bennoun-Deeds-VanValkenburgh2022) for the same reason (it has journal but not journaltitle),

### CODE REVIEW

**Comment by haraldschilly** [comment]
The problem is e6cdeb2f1729cf9ac6deb61b6ef473867e90371f and 356ef19157e964b25df9694c527aa8912d700dc6 by @dimpase … directly pushed to master without going through a PR review or testing. I've merged your PR and I'll fix these issues now. Thank you for adding this and well, sorry for the confusion.

**Comment by dimpase** [comment]
oops, sorry. I haven't understood how fragile this use of bibtex is.

**Comment by haraldschilly** [comment]
no problem … I guess this parser lib is following some old standards, I don't know.

**Comment by dimpase** [comment]
Are you using an old `pybtex`? The current version is 0.24.0

**Comment by dimpase** [comment]
it claims to be fully compatible with bibtex.

**Comment by dimpase** [comment]
hmm, no. It's a problem in the vintage `pubparse.py`...

**Comment by haraldschilly** [comment]
Well, maybe, I had 0.22.2, now updated. In any case, I was curious. There is a [biblatex.pdf](http://mirrors.ibiblio.org/CTAN/macros/latex/contrib/biblatex/doc/biblatex.pdf) (not bibtex!) and it seems to only have a `journaltitle`. I'm guessing all sane tools just automatically convert.

Screenshot from 2022-02-24 19-56-11

**Comment by dimpase** [comment]
It's a bug in `pubparse.py`:
```
aj = article.get("journal", article['journaltitle'])
```
breaks, because Python has eager parsing of arguments, and so absense of `'journaltitle'` leads to a key error straight away.

**Comment by dimpase** [comment]
Ditto in
```
ay = article.get("year", article['date'])
```

**Comment by dimpase** [comment]
OK, I'll fix these.

**Comment by JohnCremona** [comment]
Thanks @haraldschilly and @dimpase for your work on this

**Comment by dimpase** [comment]
John, perhaps you can review my fixes for `journal` stuff at #131 ?

**Comment by JohnCremona** [comment]
> John, perhaps you can review my fixes for `journal` stuff at #131 ?

OK, I am looking at it now.

**Comment by dimpase** [comment]
It's already merged by Harald :-)
It should now be easier to add bibtex entries, no more requirement of `journaltitle` etc ..

**Comment by JohnCremona** [comment]
Looking at https://www.sagemath.org/library-publications.html item 395 has a problem caused by having \mathbb{Q} in the title.

**Comment by haraldschilly** [comment]
> Looking at https://www.sagemath.org/library-publications.html item 395 has a problem caused by having \mathbb{Q} in the title.

sounds like https://github.com/sagemath/publications/issues/41, I'll make a note

**Pull request merged**
