### PR TITLE
Add new paper KLee2022

### PR DESCRIPTION
**Pull request by kwankyu**
This is also a practice of the github workflow for sage developers, as suggested in

https://groups.google.com/g/sage-devel/c/2K8BvPOE7h8

### CODE REVIEW

**Comment by kwankyu** [comment]
I put PR #143 as a "dependency".  Perhaps a workflow for "dependency" needs to be added to the migration guide.

**Comment by kwankyu** [comment]
I have no experience with github cli. But it seems that `git github` as a replacement to `git trac` would be convenient.

**Comment by haraldschilly** [comment]
ok, thx, also for fixing this integration check. the new entry in the bibliography should be live now.

**Comment by kwankyu** [comment]
Thank you!

**Pull request merged**
